- hosts: localhost
  become: true
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
  pre_tasks:
    - name: Update cache
      apt:
        update_cache: true
      tags:
        - always

  tasks:
    - import_tasks: tasks/ssh.yml
    - import_tasks: tasks/core-setup.yml
    - import_tasks: tasks/node.yml
    - import_tasks: tasks/npm-packages.yml
    - import_tasks: tasks/zsh.yml
    - import_tasks: tasks/nvim-setup.yml
    - import_tasks: tasks/dotfiles.yml
    - import_tasks: tasks/productivity.yml


