- name: Installing stow
  apt:
    name: stow
    state: present
  tags:
    &tags_for_dotfiles_tasks [ 'dotfiles', 'stow' ]

- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:andrew-theturtle/dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    accept_hostkey: true
  tags:
    *tags_for_dotfiles_tasks

- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./install
  tags:
    *tags_for_dotfiles_tasks
