- name: Get Packer
  ansible.builtin.git:
    repo: 'https://github.com/wbthomason/packer.nvim'
    dest: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
  tags:
    - packer

- name: Install PPA tooling for neovim (software-properties-common for apt_repository)
  become: true
  apt:
    name:
      - ca-certificates
      - gnupg
      - software-properties-common
    state: present
  tags:
    &tags_for_neovim_tasks [ 'neovim' ]

- name: Update apt cache
  become: true
  apt:
    update_cache: yes
  tags:
    *tags_for_neovim_tasks

- name: Install neovim
  become: true
  apt:
    name: neovim
    state: present
  tags:
    *tags_for_neovim_tasks

- name: Neovim Plugin Development 1
  become: true
  apt:
    name: luarocks
    state: present
  tags:
    - neovim-plugin

- name: Neovim Plugin Development 2 luacheck
  become: true
  shell: luarocks install luacheck
  tags:
    - neovim-plugin

- name: Install ripgrep for telescope
  become: true
  apt:
    name: ripgrep
    state: present
  tags:
    - neovim-plugin

